### ISSUE TITLE
Building for Apple Silicon

### ISSUE THREAD

**Issue by ipmb** [lincolnloop/pyuwsgi-wheels#18]
Seeing this error in GH Actions. The additional libraries we're building (pcre and libjansson) are probably getting compiled for Intel. I'm not sure how to cross-compile them.

```
   + delocate-wheel --require-archs arm64 -w /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-5t6whwq3/cp38-macosx_arm64/repaired_wheel -v /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-5t6whwq3/cp38-macosx_arm64/built_wheel/pyuwsgi-2.0.20-cp38-cp38-macosx_11_0_arm64.whl
  INFO:delocate.delocating:Copying library /usr/local/lib/libpcre.1.dylib to pyuwsgi.dylibs/libpcre.1.dylib
  INFO:delocate.delocating:Copying library /usr/local/lib/libjansson.4.dylib to pyuwsgi.dylibs/libjansson.4.dylib
  INFO:delocate.delocating:Modifying install name in pyuwsgi.cpython-38-darwin.so from /usr/local/lib/libjansson.4.dylib to @loader_path/pyuwsgi.dylibs/libjansson.4.dylib
  INFO:delocate.delocating:Modifying install name in pyuwsgi.cpython-38-darwin.so from /usr/local/lib/libpcre.1.dylib to @loader_path/pyuwsgi.dylibs/libpcre.1.dylib
  Fixing: /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-5t6whwq3/cp38-macosx_arm64/built_wheel/pyuwsgi-2.0.20-cp38-cp38-macosx_11_0_arm64.whl
  Traceback (most recent call last):
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-5t6whwq3/cp38-macosx_arm64/build/venv/bin/delocate-wheel", line 8, in <module>
      sys.exit(main())
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-5t6whwq3/cp38-macosx_arm64/build/venv/lib/python3.8/site-packages/delocate/cmd/delocate_wheel.py", line 128, in main
      copied = delocate_wheel(
    File "/private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-5t6whwq3/cp38-macosx_arm64/build/venv/lib/python3.8/site-packages/delocate/delocating.py", line 662, in delocate_wheel
      raise DelocationError(
  delocate.delocating.DelocationError: Some missing architectures in wheel
  Required arch arm64 missing from pyuwsgi.cpython-38-darwin.so
Error: Command delocate-wheel --require-archs arm64 -w /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-5t6whwq3/cp38-macosx_arm64/repaired_wheel -v /private/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/cibw-run-5t6whwq3/cp38-macosx_arm64/built_wheel/pyuwsgi-2.0.20-cp38-cp38-macosx_11_0_arm64.whl failed with code 1. None
```

**Comment by asottile** [comment]
via #25
